pcap: false

bag: true

bag_args: 

topics: /tf /tf_static /fast_limo/body /fast_limo/deskewed /fast_limo/final_raw /fast_limo/match /fast_limo/match_points /fast_limo/original /fast_limo/pointcloud /fast_limo/state

pcap_args: 

pcap_name:

bag_name: rosbag_ID

date_format: "%Y_%m_%d-%H_%M_%S"
